workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build (Limited HERE SDK Support)
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      xcode: latest
    scripts:
      - name: Install Git LFS
        script: brew install git-lfs
      - name: Initialize LFS
        script: git lfs install
      - name: Pull LFS files
        script: git lfs pull
      - name: Clean Flutter
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install iOS Pods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS Simulator (Limited)
        script: |
          echo "WARNING: HERE SDK has limited simulator support"
          echo "Building without HERE SDK features for simulator testing"
          flutter build ios --simulator --debug --no-obfuscate
